[package]
name = "rs-sudoku"
version = "0.2.0"
authors = ["dotcs <git@dotcs.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
itertools = "0.9.0"
log = "0.4.11"
